export const FILTERS_MAP = {
  hotelAvailability: 'Доступность отеля',
  region: 'Регион',
  hotelNameSearch: 'Поиск по названию отеля',
  hotelCategory: 'Категория отеля',
  mealType: 'Тип питания',
  hotelConcept: 'Концепция отеля',
  price: 'Цена',
  specialOffers: 'Акции и спецпредложения',
  recommendedHotels: 'Рекомендуемые отели',
  hotelInfo: 'Информация об отеле',
  totalArea: 'Общая площадь',
  distanceToBeach: 'Расстояние до пляжа (м)',
  distanceToAirport: 'Расстояние до аэропорта (км)',
  distanceToCityCenter: 'Расстояние до центра города (км)',
  beach: 'Пляж',
  poolsAndWaterpark: 'Бассейны и аквапарк',
  forChildren: 'Для детей',
  hotelServices: 'Услуги отеля',
  roomAmenities: 'Оснащение номера',
  roomType: 'Тип номера',
  additionalOptions: 'Дополнительные опции',
};
