export const COUNTRY_MAP = {
	tr: "Турция",
	ae: "ОАЭ",
	eg: "Египет",
	vn: "Вьетнам",
	cu: "Куба",
	mu: "Маврикий",
	my: "Малайзия",
	mv: "Мальдивы",
	ma: "Марокко",
	mx: "Мексика",
	ru: "Россия",
	th: "Таиланд",
	tz: "Танзания",
	tn: "Тунис",
	uz: "Узбекистан",
	ph: "Филиппины",
	lk: "Шри-Ланка",
	az: "Азербайджан",
	am: "Армения",
	bh: "Бахрейн",
	by: "Беларусь",
	bg: "Болгария",
	ge: "Грузия",
	do: "Доминикана",
	in: "Индия",
	gr: "Греция",
	ab: "Абхазия",
	ad: "Андорра",
	jo: "Иордания",
	es: "Испания",
	id: "Индонезия",
	it: "Италия",
	kz: "Казахстан",
	cy: "Кипр",
	cn: "Китай",
	sc: "Сейшелы",
	me: "Черногория",
	hr: "Хорватия",
};

export const DEPARTURE_MAP = {
	msk: "Москва",
	abn: "Абакан",
	arh: "Архангельск",
	ast: "Астрахань",
	bar: "Барнаул",
	blg: "Благовещенск",
	vlv: "Владивосток",
	vlg: "Волгоград",
	grz: "Грозный",
	ekb: "Екатеринбург",
	izv: "Ижевск",
	irk: "Иркутск",
	kzn: "Казань",
	klg: "Калининград",
	kem: "Кемерово",
	krr: "Красноярск",
	mag: "Магадан",
	mgn: "Магнитогорск",
	mah: "Махачкала",
	kmv: "Минеральные воды",
	myr: "Мурманск",
	nzg: "Н. Новгород",
	nvk: "Нижневартовск",
	nkk: "Нижнекамск",
	nkz: "Новокузнецк",
	nov: "Новосибирск",
	omc: "Омск",
	orb: "Оренбург",
	pem: "Пермь",
	ptr: "Петропавловск-Камчатский",
	smr: "Самара",
	spb: "Санкт-Петербург",
	srt: "Саратов",
	sch: "Сочи",
	stv: "Ставрополь",
	srg: "Сургут",
	sik: "Сыктывкар",
	tom: "Томск",
	tum: "Тюмень",
	yln: "Ульяновск",
	yfa: "Уфа",
	hab: "Хабаровск",
	hmn: "Ханты-Мансийск",
	chl: "Челябинск",
	ush: "Южно-Сахалинск",
	yak: "Якутск",
	yar: "Ярославль",
};

export const ARRIVAL_MAP = {
	"Турция": ["1-0", "turtsiya"],
	"ОАЭ": ["31-0", "oae"],
	"Египет": ["12-0", "egipet"],
	"Вьетнам": ["41-0", "vyetnam"],
	"Куба": ["48-0", "kuba"],
	"Маврикий": ["63-0", "mavrikiy"],
	"Малайзия": ["118-0", "malayziya"],
	"Мальдивы": ["35-0", "malydivy"],
	"Марокко": ["45-0", "marokko"],
	"Мексика": ["98-0", "meksika"],
	"Россия": ["3-0", "rossiya"],
	"Таиланд": ["33-0", "tailand"],
	"Танзания": ["60-0", "tanzaniya"],
	"Тунис": ["34-0", "tunis"],
	"Узбекистан": ["49-0", "uzbekistan"],
	"Филиппины": ["251-0", "filippiny"],
	"Шри-Ланка": ["40-0", "shrilanka"],
	"Азербайджан": ["7-0", "azerbaydzhan"],
	"Армения": ["5-0", "armeniya"],
	"Бахрейн": ["282-0", "bahreyn"],
	"Беларусь": ["8-0", "belarus"],
	"Болгария": ["10-0", "bolgariya"],
	"Грузия": ["15-0", "gruziya"],
	"Доминикана": ["36-0", "dominikanskayarespublika"],
	"Индия": ["52-0", "indiya"],
	"Греция": ["43-0", "gretsiya"],
	"Абхазия": ["278-0", "abhaziya"],
	"Андорра": ["72-0", "andorra"],
	"Иордания": ["58-0", "iordaniya"],
	"Испания": ["112-3-42_72", "barselona"],
	"Индонезия": ["38-0", "indoneziya"],
	"Италия": ["18-0", "italiya"],
	"Казахстан": ["19-0", "kazahstan"],
	"Кипр": ["216-0", "kipr"],
	"Китай": ["37-0", "kitay"],
	"Сейшелы": ["39-0", "seyshely"],
	"Черногория": ["80-0", "chernogoriya"],
	"Хорватия": ["108-0", "horvatiya"],
};

export const FILTERS = {
	available: {
		type: 21,
		values: [{id: "2", value: "2", parent: null}],
		providers: null,
	},
	ai: {
		type: 5,
		values: [
			{id: "1", value: "1", parent: null},
			{id: "2", value: "2"},
		],
		providers: [],
	},
	elite: {
		type: 3,
		values: [
			{id: "49", value: "49", parent: null},
			{id: "1", value: "1", parent: null},
		],
		providers: null,
	},
	family: {
		type: 3,
		values: [{id: "5", value: "5", parent: null}],
		providers: null,
	},
	["50m"]: {
		type: 25,
		values: [{id: "0-50", value: "0-50", parent: null}],
		providers: null,
	},
	["250m"]: {
		type: 25,
		values: [{id: "50-250", value: "50-250", parent: null}],
		providers: null,
	},
	["5stars"]: {
		type: 2,
		values: [{id: "5", value: "5", parent: null}],
		providers: null,
	},
	privatebeach: {
		type: 6,
		values: [{id: "32", value: "32", parent: null}],
		providers: null,
		parent: [
			{
				id: "3",
				value: "3",
				parent: null,
				providers: [],
			},
		],
	},
};
